-- WorldBossAuraSystem Config
-- Override values here to customize boss behavior.
-- Uncomment and modify any field below.

-- return {
--     enabled = true,
--     log = true,
--     SpawnIntervalSeconds = 1800,
--     BossScale = 3.0,
--     CapturedScale = 2.0,
--     HpMultiplier = 100,
--     AtkMultiplier = 2,
--     DefMultiplier = 2,
--     CapturedTalent = 200,
--     DaemonPort = 8215,
--     NotifyToast = true
-- }
